{% macro price_cat(P_PRICE_PER_NIGHT) %}
  CASE
    WHEN {{ P_PRICE_PER_NIGHT }} BETWEEN 1 AND 100 THEN 'BUDGET'
    WHEN {{ P_PRICE_PER_NIGHT }} BETWEEN 100 AND 200 THEN 'MID-RANGE'
    WHEN {{ P_PRICE_PER_NIGHT }} BETWEEN 200 AND 300 THEN 'PREMIUM'
    ELSE 'ULTRA PREMIUM'
  END
{% endmacro %}