CREATE OR REPLACE STORAGE INTEGRATION S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = '<aws_snowflake_role_arn>'
STORAGE_ALLOWED_LOCATIONS = ('<your_aws_bucket_location>');

-- check the PARAMETERS OF AWS ingration file

DESC STORAGE INTEGRATION  S3_INT;