{{ config(materialized='ephemeral') }}

with hosts as (
SELECT HOST_ID,
HOST_NAME,
HOST_SINCE,
HOST_TENURE_MONTHS,
IS_SUPERHOST,
RESPONSE_RATE_CATEGORY,
HOST_CREATED_AT FROM (
select HOST_ID,
HOST_NAME,
HOST_SINCE,
HOST_TENURE_MONTHS,
IS_SUPERHOST,
RESPONSE_RATE_CATEGORY,
HOST_CREATED_AT  , ROW_NUMBER() OVER (PARTITION BY HOST_ID,
HOST_NAME,
HOST_SINCE,
HOST_TENURE_MONTHS,
IS_SUPERHOST,
RESPONSE_RATE_CATEGORY,
HOST_CREATED_AT ORDER BY HOST_ID) RK
FROM {{ ref('OBT')  }}
) WHERE RK = 1  ORDER BY HOST_ID 
) select * from hosts